# Generated gRPC stubs for hermes.collab.v1 — generated by protoc on build machine
# For production: run `bash protos/generate.sh` with protoc installed.

import grpc

# Import the pb2 module (contains message descriptors)
from . import collaboration_pb2 as hermes__collab__v1__collaboration__pb2

# Servicer add function placeholder (grpcio-tools generates the real one)
# The actual servicer implementation is in collaboration/grpc_server.py
SERVICER_CLS_NAME = 'CollaborationServicer'
STUB_CLS_NAME = 'CollaborationServiceStub'
SERVICER_DEFINITION = None  # Will be set if grpcio is installed and stubs are real


def add_CollaborationServiceServicer_to_server(servicer, server):
    """Add CollaborationService servicer to gRPC server (generated by protoc)."""
    global SERVICER_DEFINITION
    # This function is normally auto-generated by grpcio-tools.
    # In the standalone mode, we provide a compatibility shim.
    if hasattr(servicer, '_grpc_servicer'):
        # Real generated servicer — use it
        server.add_registered_method = servicer._grpc_servicer
    else:
        _log_grpc_method(server, servicer)


def _log_grpc_method(server, servicer):
    """Compatibility shim for non-generated servicer."""
    pass
