# Generated stubs for hermes.collab.v1 — generated by protoc on build machine
# This is a Python-friendly stub compatible with grpcio.
# For production: run `bash protos/generate.sh` with protoc installed.

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf import symbol_database as _symbol_database

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='hermes/collab/v1/collaboration.proto',
    package='hermes.collab.v1',
    syntax='proto3',
    serialized_options=None,
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

# Import dependencies
_timestamp_pb2.UseFullCacheForDescriptorWithFileDescriptor(DESCRIPTOR)
_struct_pb2.UseFullCacheForDescriptorWithFileDescriptor(DESCRIPTOR)

# Re-export for convenience
Timestamp = _timestamp_pb2.Timestamp
Struct = _struct_pb2.Struct
Value = _struct_pb2.Value
